### ISSUE TITLE
File "app/updater/ota_updater.py", line 137, in _download_all_files TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by FalconBFR** [rdehuyss/micropython-ota-updater#17]
`File "app/updater/ota_updater.py", line 137, in _download_all_files
TypeError: string indices must be integers, not str`

Did I make a setup error? I will try my best to debug this on my end. 
My testing repo is here btw. Thanks!
https://github.com/FalconBFR/esp32otatestv3

My Line 137 is:
`path = self.modulepath(self.new_version_dir + '/' + file['path'].replace(self.main_dir + '/', '').replace(self.github_src_dir, ''))
`

Full Trace:
```
Checking version... 
	Current version:  0.0
	Latest version:  3
Updating to version 3...
Downloading version 3
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "app/onstart.py", line 34, in <module>
  File "app/onstart.py", line 23, in connectToWifiAndUpdate
  File "app/updater/ota_updater.py", line 78, in install_update_if_available
  File "app/updater/ota_updater.py", line 129, in _download_new_version
  File "app/updater/ota_updater.py", line 137, in _download_all_files
TypeError: string indices must be integers, not str
MicroPython v1.14 on 2021-02-02; ESP32 module with ESP32
Type "help()" for more information.
```
Btw, the date on the board is wrong for some reason. Please ignore. Thanks.

**Comment by FalconBFR** [comment]
Debugging in progress:
Changed func to:
```def _download_all_files(self, version, sub_dir=''):
        url = 'https://api.github.com/repos/{}/contents{}{}{}?ref=refs/tags/{}'.format(self.github_repo, self.github_src_dir, self.main_dir, sub_dir, version)
        gc.collect() 
        file_list = self.http_client.get(url)
        for file in file_list.json():
            #self added to debug
            temp_file_path = file['path'].replace(self.main_dir + '/', '')
            print("done 1")
            print(temp_file_path)
            temp_file_path = temp_file_path.replace(self.github_src_dir, '')
            print("done 2")
            print(temp_file_path)
            path = self.modulepath(self.new_version_dir + '/' + temp_file_path)
            #path = self.modulepath(self.new_version_dir + '/' + file['path'].replace(self.main_dir + '/', '').replace(self.github_src_dir, ''))
            if file['type'] == 'file':
                gitPath = file['path']
                print('\tDownloading: ', gitPath, 'to', path)
                self._download_file(version, gitPath, path)
            elif file['type'] == 'dir':
                print('Creating dir', path)
                self.mkdir(path)
                self._download_all_files(version, sub_dir + '/' + file['name'])
            gc.collect()

        file_list.close()```

Identified Issue to L138(self amended version): `temp_file_path = file['path'].replace(self.main_dir + '/', '')`

**Comment by FalconBFR** [comment]
Issue identified: 
`file['path']` produces an error

**Comment by FalconBFR** [comment]
print(file) 
output: `message`

print(type(file))
output: `<class 'str'>`

**Comment by FalconBFR** [comment]
Tracing to earlier line:
`file_list = self.http_client.get(url)`(135)

print(file_list)
output: {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/repos#get-repository-content'}

**Comment by FalconBFR** [comment]
Issue Identified.Github source directory incorrectly specified
Added: `github_src_dir='src'`
otaUpdater = OTAUpdater('https://github.com/user/reponame', github_src_dir='src',main_dir='app')
