### ISSUE TITLE
Connection errors [solved]

### ISSUE THREAD

**Issue by ebolisa** [rdehuyss/micropython-ota-updater#23]
Hi and thanks for sharing.
I'd appreciate if you can help me out with the following error.
Thank you.

`Memory free 81936
network config: ('192.168.1.30', '255.255.255.0', '192.168.1.1', '212.166.210.82')
Checking version... 
	Current version:  0.6.1
	Latest version:  1.0.0
Updating to version 1.0.0...
Downloading version 1.0.0
Traceback (most recent call last):
  File "<stdin>", line 30, in <module>
  File "<stdin>", line 19, in connectToWifiAndUpdate
  File "app/ota_updater.py", line 78, in install_update_if_available
  File "app/ota_updater.py", line 129, in _download_new_version
  File "app/ota_updater.py", line 137, in _download_all_files
TypeError: string indices must be integers, not str`

**Comment by ebolisa** [comment]
Nevermind. Had an error with the github link ):

**Comment by rdehuyss** [comment]
Since you changed the title to solved, I assume it is solved? Closing this as part of spring clean.
