### ISSUE TITLE
Possible issue with library

### ISSUE THREAD

**Issue by ebolisa** [rdehuyss/micropython-ota-updater#24]
Hi,
Can someone help me out understanding why the lib is crushing?
TIA
`Checking version... 
	Current version:  0.0
	Latest version:  1.0.0
Updating to version 1.0.0...
Downloading version 1.0.0
Traceback (most recent call last):
  File "<stdin>", line 33, in <module>
  File "<stdin>", line 18, in Update
  File "app/ota_updater.py", line 81, in install_update_if_available
  File "app/ota_updater.py", line 132, in _download_new_version
  File "app/ota_updater.py", line 140, in _download_all_files
TypeError: string indices must be integers, not str`

**Comment by rikvermeer** [comment]
The string replacement in the ota_updater that reads json from the github file is corrupt. First of all, it tells nothing about whether it could read your github json directive. Try adding some debug info to the file so you see what URL's it uses and check them manually.

After this phase there should also be no more errors in the httpclient Response class due to the socket being closed or None.

Furthermore... the string replacement that happens after it found the first github directive really messed things up for me. In my case the "main" dir and the "github_src_dir" respectively were "main" and "app/main". The string replacer did replace("main", '').replace('app/main', '') or something... please check it out what the results are for you. For me it created paths like "/main/app/main" and such while i really just wanted "/main".

Overall this script is really handy.
@rdehuyss willing to help

**Comment by rikvermeer** [comment]
This line must also be incorrect when using non-default paths:

**Comment by rdehuyss** [comment]
@rikvermeer feel free to create a PR but my time is currently limited. If you do so, please make sure to test it well as I won't have the time to do so.
