### ISSUE TITLE
Read tag version from private

### ISSUE THREAD

**Issue by suysh** [rdehuyss/micropython-ota-updater#9]
The script can read the version for public repositories, but when I try to read from a private one (use with token) I get following error:
```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
  File "main.py", line 20, in boot
  File "main.py", line 9, in download_and_install_update_if_available
  File "main/ota_updater.py", line 32, in check_for_update_to_install_during_next_reboot
  File "main/ota_updater.py", line 116, in get_latest_version
KeyError: tag_name

```
Any ideas why?
Kind regards, Hans

**Comment by suysh** [comment]
Solved, sorry to create an issue.
The token should have the correct rights (select the scopes).
Kind regards, Hans
